### ISSUE TITLE
Удалить избыточные зависимости шаблонов gitlab-ci.

### ISSUE THREAD

**Issue by vedorofeev** [egal/gitlab-ci#2]
`proxy:deploy` ожидает выполнения `core-service:deploy`, которого может не быть. и он не используется в скрипте деплоя прокси.
Также `proxy:deploy` ожидает выполнения  `auth-service:deploy`, который не используется в скрипте деплоя прокси.

В файле `deploy-needs-build.yml.stub`:
 - нужно удалить ожидание `__SERVICE_NAME__:build-service-image`, т.к. также эта задача ожидает исполнение `__SERVICE_NAME__:migration`, которая в свою очередь уже зависит от  `__SERVICE_NAME__:build-service-image`.
 - нужно удалить ожидание `create-docker-network`, т.к. также эта задача ожидает исполнение `rabbitmq:deploy`, которая в свою очередь уже зависит от  `create-docker-network`.

Помимо этого стоит проверить остальные stub файлы

**Comment by rollsover** [comment]
Последние два кейса игнорируем, так как не вижу противоречий по кодовой базе

`create-docker-network` needs `prepare`
`build-service-image` needs `prepare`
`rabbitmq:deploy` needs `rabbitmq:pull-service-image`, `create-docker-network`
`deploy` needs `build-service-image`, `migration`, ` create-docker-network`, `rabbitmq:deploy`

**Comment by vedorofeev** [comment]
Всё работает
